AWSTemplateFormatVersion: '2010-09-09'
Description: Launch an EC2 instance in the free tier 
#-------------------------- Parameters --------------------------#
Parameters:
  KeyPairName:
    Description: Name of an existing EC2 key pair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
  
  VpcId:
    Description: ID of the VPC where the instance should be launched
    Type: AWS::EC2::VPC::Id
  
  SubnetIdRashbagWebServer1:
    Description: ID of the public subnet where the instance should be launched
    Type: AWS::EC2::Subnet::Id
  
  SubnetIdRashbagWebServer2:
    Description: ID of the public subnet where the instance should be launched
    Type: AWS::EC2::Subnet::Id

  SubnetIdRashbagprivate1:
    Description: ID of the private subnet where the instance should be launched
    Type: AWS::EC2::Subnet::Id  
  
  SubnetIdRashbagprivate2:
    Description: ID of the private subnet where the instance should be launched
    Type: AWS::EC2::Subnet::Id
  
  SecurityGroupIdPublic:
    Description: ID of the security group to associate with the instance
    Type: AWS::EC2::SecurityGroup::Id

  SecurityGroupIdPrivate:
    Description: ID of the security group to associate with the instance
    Type: AWS::EC2::SecurityGroup::Id

#-------------------------- Resources --------------------------#
Resources:

  #________ IAM Roles _________#
  S3FullAccessRoleForEC2:  # New IAM role definition (assuming not created yet)
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: S3FullAccessRoleForEC2
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: S3FullAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                Resource:
                  - '*'

  #________ Instance Profile _________#

  S3FullAccessInstanceProfile:  # New resource for instance profile
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - S3FullAccessRoleForEC2  # Reference the created IAM role
    DependsOn: S3FullAccessRoleForEC2  # This ensures role is created first

  #________ Load Balancer _________#
  # Application Load Balancer Resources
  # ----------------------------------- #
  # This template creates an Application Load Balancer (ALB)
  # and attaches it to a Target Group containing a pair of
  # EC2 instances. The ALB listens on port 80 and forwards incoming
  # traffic to the Target Group.
  # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ #
  WebServerALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing  # Make the ALB publicly accessible
      SecurityGroups:
        - !Ref SecurityGroupIdPublic
      Subnets:
        - !Ref SubnetIdRashbagWebServer1
        - !Ref SubnetIdRashbagWebServer2

  WebServerALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward  # Forward incoming traffic to the Target Group
          TargetGroupArn: !Ref WebServerALBTargetGroup
      LoadBalancerArn: !Ref WebServerALB
      Port: 80  # Listen on port 80 for incoming traffic
      Protocol: HTTP

  WebServerALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /  # Use the root URL for health checks
      Port: 80  # Target Group will forward traffic to port 80 of its targets
      Protocol: HTTP
      TargetType: instance  # Targets are EC2 instances
      VpcId: !Ref VpcId

  # Auto Scaling Group Resources
  # ----------------------------------- #
  # This template creates an Auto Scaling Group (ASG) that will
  # launch and terminate EC2 instances based on CPU utilization.
  # The ASG will launch at least 2 instances and at most 4
  # instances, and will add or remove instances as needed to keep
  # CPU utilization at 50%.
  # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ #
  WebServerASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:  # Launch instances in these subnets
        - !Ref SubnetIdRashbagWebServer1
        - !Ref SubnetIdRashbagWebServer2
      LaunchConfigurationName: !Ref WebServerLaunchConfiguration
      MinSize: 2  # Launch at least this many instances
      MaxSize: 4  # Launch at most this many instances
      TargetGroupARNs:  # Attach the Target Group to the ASG
        - !Ref WebServerALBTargetGroup

  WebServerLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0aa7d40eeae50c9a9  # Amazon Linux 2 AMI
      InstanceType: t2.micro  # Free tier instance type
      KeyName: !Ref KeyPairName
      SecurityGroups:
        - !Ref SecurityGroupIdPublic  # Attach to this security group
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Install the necessary packages and start the web server
          yum update -y
          yum install git -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          # Clone the sample app and move its files to the web server root
          cd /var/www/html/
          git clone "https://github.com/LiorTr/crypto.git"
          mv -f ./crypto/* .
          rm -rf crypto

  WebServerASGCPUPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref WebServerASG  # Apply the policy to the ASG
      PolicyType: TargetTrackingScaling  # Scale based on CPU utilization
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization  # Target 50% CPU utilization
        TargetValue: 50.0

  WebServerASGCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm monitoring CPU utilization on EC2 instances"
      Namespace: AWS/EC2  # Monitor CPU utilization of EC2 instances
      MetricName: CPUUtilization
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref WebServerASG  # Monitor the instances in this ASG
      Statistic: Average
      Period: 300  # Check CPU utilization every 5 minutes
      EvaluationPeriods: 2  # Check utilization for at least 2 periods
      Threshold: 80  # If utilization is above 80%, trigger the alarm
      ComparisonOperator: GreaterThanThreshold  # Trigger the alarm if above threshold
      AlarmActions:
        - !Ref WebServerASGCPUPolicy  # When the alarm triggers, scale the ASG
  
  #________ EC2 Private Instances _________#
  PrivateInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0aa7d40eeae50c9a9 # Amazon Linux 2 AMI (Free Tier)
      InstanceType: t2.micro # Free Tier instance type
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref S3FullAccessInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet:
            - !Ref SecurityGroupIdPrivate
          SubnetId: !Ref SubnetIdRashbagprivate1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Create a new S3 bucket
          BUCKET_NAME="rashbag-ec2"
          aws s3 mb s3://$BUCKET_NAME
          # Create a file with the content "hello world"
          echo "hello world" > rashbag.txt
          # Upload the file to the new bucket
          aws s3 cp rashbag.txt s3://$BUCKET_NAME/
      Tags:
        - Key: Name
          Value: "Rashbag-private-1"

  PrivateInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0aa7d40eeae50c9a9 # Amazon Linux 2 AMI (Free Tier)
      InstanceType: t2.micro # Free Tier instance type
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet:
            - !Ref SecurityGroupIdPrivate
          SubnetId: !Ref SubnetIdRashbagprivate2
      Tags:
        - Key: Name
          Value: "Rashbag-private-2"

#-------------------------- Outputs --------------------------#
Outputs:
  WebServerALBDNSName:
    Description: The DNS name of the Application Load Balancer
    Value: !GetAtt WebServerALB.DNSName

  PrivateInstance1Id:
    Description: The instance ID of the first private instance
    Value: !Ref PrivateInstance1

  PrivateInstance2Id:
    Description: The instance ID of the second private instance
    Value: !Ref PrivateInstance2