AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.

Resources:
  Resizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://resizer-function/function.zip  # Updated CodeUri with S3 location
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          DEST_BUCKET: !ImportValue Rashbag-S3-S3BucketDstName
      Role: arn:aws:iam::992382501873:role/S3FullAccessRoleLambda

  S3Trigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !ImportValue Rashbag-S3-S3BucketSrcARN  # Replace with actual bucket ARN
      FunctionName: !GetAtt Resizer.Arn  # ARN of Resizer
      BatchSize: 1  # Optional: Number of events delivered per invocation
      # You can add filtering for specific events using "FilterPolicy" property
