#---------------S3------------------#
AWSTemplateFormatVersion: '2010-09-09'
Description: Launch an EC2 instance in the free tier


Parameters:
#------------------------ Parameters --------------------------#
  S3BucketDstName:
    Description: Name for the S3 bucket
    Type: String
    Default: rashbags-s3-dst

  S3BucketSrcName:
    Description: Name for the S3 bucket
    Type: String
    Default: rashbag-s3-src

Resources:
# ---- S3 Buckets ----- #
  S3BucketDst:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref S3BucketDstName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  S3BucketSrc:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref S3BucketSrcName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

Outputs: # Corrected Section Name
#------------------------ Outputs --------------------------#
  S3BucketDstARN:
    Value: !GetAtt S3BucketDst.Arn  # Use 'Arn' instead of 'ARN'
    Description: The ARN of the S3 bucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketDstARN'

  S3BucketSrcARN:
    Value: !GetAtt S3BucketSrc.Arn  # Use 'Arn' instead of 'ARN'
    Description: The ARN of the S3 bucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketSrcARN'