AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for a Lambda function triggered by S3

#-------------------------- Resources --------------------------#
Resources:
# Source S3 Bucket
  S3BucketSrc:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !ImportValue Rashbag-S3-S3BucketSrcName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !ImportValue resizer-function-ResizerFunctionArn